{% set name = "dtool_lookup_api" %}
{% set version = "0.5.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/dtool-lookup-api/dtool-lookup-api-{{ version }}.tar.gz
  sha256: 607acc0dce3ec1bc28d2c2f7de8ca7a01bd3775fef89e36bb5d5f99af33b40ee

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools_scm
  run:
    - aiohttp
    - asgiref
    - dtoolcore >=3.9.0
    - python >=3.6
    - pyyaml

test:
  imports:
    - dtool_lookup_api
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/IMTEK-Simulation/dtool-lookup-api
  summary: This package offers both synchronous and asynchronous implementations of a standardized Python API to communicate with the dtool lookup server.
  license: MIT
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - jan-janssen
