{% set name = "dtool_lookup_api" %}
{% set version = "0.8.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/dtool-lookup-api/{{ name }}-{{ version }}.tar.gz
  sha256: 548d56fb08e8180606c2af84cf504453ece648133ce7399b63963cf3ffad968b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools_scm
  run:
    - aiohttp
    - asgiref
    - dtoolcore >=3.9.0
    - python >=3.6
    - pyyaml

test:
  imports:
    - dtool_lookup_api
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/IMTEK-Simulation/dtool-lookup-api
  summary: This package offers both synchronous and asynchronous implementations of a standardized Python API to communicate with the dtool lookup server.
  license: MIT
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - jan-janssen
