{% set name = "dtool_lookup_api" %}
{% set version = "0.10.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/dtool-lookup-api/{{ name }}-{{ version }}.tar.gz
  sha256: 6880f019b947269494b1e4d20171a1d82a277a788bd0bdfb600900cfab165305

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
    - setuptools_scm
  run:
    - certifi
    - aiohttp
    - asgiref
    - dtoolcore >=3.9.0
    - python >=3.6
    - setuptools
    - pyyaml

test:
  imports:
    - dtool_lookup_api
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/IMTEK-Simulation/dtool-lookup-api
  summary: This package offers both synchronous and asynchronous implementations of a standardized Python API to communicate with the dtool lookup server.
  license: MIT
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - jan-janssen
